import { MaintenanceScheduleStatus } from '@prisma/client';
import { AppError } from '../../shared/errors/AppError';
import { AuditService } from '../../shared/services/audit.service';
import type { RequestActor } from '../../shared/http/RequestActor';
import { MaintenanceRepository } from './maintenance.repository';
import type { CreatePlanInput, UpdatePlanInput, LinkEquipmentInput, CreateScheduleInput, UpdateScheduleInput, UpdateScheduleStatusInput, CreateIntervalInput, ListSchedulesQueryInput } from './maintenance.schema';

const transitions: Record<MaintenanceScheduleStatus, MaintenanceScheduleStatus[]> = { SCHEDULED: ['DUE', 'CANCELLED'], DUE: ['OVERDUE', 'IN_PROGRESS', 'CANCELLED'], OVERDUE: ['IN_PROGRESS', 'CANCELLED'], IN_PROGRESS: ['COMPLETED', 'CANCELLED'], COMPLETED: [], CANCELLED: [] };
export class MaintenanceService {
  constructor(private readonly repo: MaintenanceRepository, private readonly audit: AuditService) {}
  private org(a: RequestActor) { if (!a.organizationId) throw new AppError('Escopo organizacional não informado.', 403, 'ORGANIZATION_SCOPE_REQUIRED'); return a.organizationId; }
  private log(a: RequestActor, type: string, id: string, action: string, data?: Record<string, unknown>) { return this.audit.log({ actor: a, module: 'maintenance', entityType: type, entityId: id, action, newData: data }); }
  async listPlans(a: RequestActor) { return this.repo.listPlans(this.org(a)); }
  async getPlan(a: RequestActor, id: string) { const r = await this.repo.findPlan(id, this.org(a)); if (!r) throw new AppError('Plano não encontrado.', 404, 'NOT_FOUND'); return r; }
  async createPlan(a: RequestActor, i: CreatePlanInput) { const r = await this.repo.createPlan({ organizationId: this.org(a), code: i.code, name: i.name, description: i.description, createdByUserId: a.userId, intervals: i.intervals ? { create: i.intervals } : undefined }); await this.log(a, 'MaintenancePlan', r.id, 'CREATED'); return r; }
  async updatePlan(a: RequestActor, id: string, i: UpdatePlanInput) { const { intervals, ...data } = i; const updateData: any = { ...data }; if (intervals) updateData.intervals = { deleteMany: {}, create: intervals }; const r = await this.repo.updatePlan(id, this.org(a), updateData); if (!r) throw new AppError('Plano não encontrado.', 404, 'NOT_FOUND'); await this.log(a, 'MaintenancePlan', id, 'UPDATED'); return r; }
  async archivePlan(a: RequestActor, id: string) { if (!(await this.repo.archivePlan(id, this.org(a)))) throw new AppError('Plano não encontrado.', 404, 'NOT_FOUND'); await this.log(a, 'MaintenancePlan', id, 'ARCHIVED'); return { id, archived: true }; }
  async addInterval(a: RequestActor, id: string, i: CreateIntervalInput) { if (!(await this.repo.findPlan(id, this.org(a)))) throw new AppError('Plano não encontrado.', 404, 'NOT_FOUND'); return this.repo.createInterval({ ...i, maintenancePlanId: id }); }
  async updateInterval(a: RequestActor, id: string, i: CreateIntervalInput) { const r = await this.repo.updateInterval(id, this.org(a), i); if (!r) throw new AppError('Intervalo não encontrado.', 404, 'NOT_FOUND'); return r; }
  async listLinks(a: RequestActor, id: string) { if (!(await this.repo.findPlan(id, this.org(a)))) throw new AppError('Plano não encontrado.', 404, 'NOT_FOUND'); return this.repo.listLinks(id, this.org(a)); }
  async linkEquipment(a: RequestActor, planId: string, i: LinkEquipmentInput) { const o = this.org(a); if (!(await this.repo.findPlan(planId, o)) || !(await this.repo.findEquipment(i.equipmentId, o))) throw new AppError('Plano ou equipamento não encontrado.', 404, 'NOT_FOUND'); if (await this.repo.findLink(i.equipmentId, planId, o)) throw new AppError('Equipamento já vinculado.', 409, 'DUPLICATE_RECORD'); const r = await this.repo.createLink({ ...i, organizationId: o, maintenancePlanId: planId, startDate: i.startDate || new Date() }); await this.log(a, 'MaintenancePlanEquipment', r.id, 'LINKED'); return r; }
  async unlinkEquipment(a: RequestActor, id: string) { if (!(await this.repo.deleteLink(id, this.org(a)))) throw new AppError('Vínculo não encontrado.', 404, 'NOT_FOUND'); await this.log(a, 'MaintenancePlanEquipment', id, 'UNLINKED'); return { id, removed: true }; }
  async listSchedules(a: RequestActor, q: ListSchedulesQueryInput) { return this.repo.listSchedules(this.org(a), q); }
  async getSchedule(a: RequestActor, id: string) { const r = await this.repo.findSchedule(id, this.org(a)); if (!r) throw new AppError('Agendamento não encontrado.', 404, 'NOT_FOUND'); return r; }
  async createSchedule(a: RequestActor, i: CreateScheduleInput) { const o = this.org(a); if (!(await this.repo.findEquipment(i.equipmentId, o))) throw new AppError('Equipamento não encontrado.', 404, 'NOT_FOUND'); if (i.maintenancePlanId && !(await this.repo.findPlan(i.maintenancePlanId, o))) throw new AppError('Plano não encontrado.', 404, 'NOT_FOUND'); if (i.workOrderId && !(await this.repo.findWorkOrder(i.workOrderId, o))) throw new AppError('OS não encontrada.', 404, 'NOT_FOUND'); const r = await this.repo.createSchedule({ ...i, organizationId: o, code: `MNT-${Date.now()}`, status: MaintenanceScheduleStatus.SCHEDULED }); await this.log(a, 'MaintenanceSchedule', r.id, 'SCHEDULED'); return r; }
  async updateSchedule(a: RequestActor, id: string, i: UpdateScheduleInput) { const r = await this.repo.updateSchedule(id, this.org(a), i); if (!r) throw new AppError('Agendamento não encontrado.', 404, 'NOT_FOUND'); await this.log(a, 'MaintenanceSchedule', id, i.scheduledDate ? 'RESCHEDULED' : 'UPDATED'); return r; }
  async updateStatus(a: RequestActor, id: string, i: UpdateScheduleStatusInput) { const c = await this.getSchedule(a, id); if (!transitions[c.status].includes(i.status)) throw new AppError('Transição inválida.', 409, 'INVALID_STATUS_TRANSITION'); const r = await this.repo.updateSchedule(id, this.org(a), { status: i.status, canceledReason: i.canceledReason, completedAt: i.status === 'COMPLETED' ? new Date() : undefined }); await this.log(a, 'MaintenanceSchedule', id, i.status === 'COMPLETED' ? 'COMPLETED' : i.status === 'CANCELLED' ? 'CANCELLED' : 'STATUS_CHANGED'); return r; }
}

